SOURCES = {
    'Pitchfork': {
        'tier': 1,
        'authority': 8,
        'region': 'US',
        'kind': 'editorial',
        'feeds': [
            'https://pitchfork.com/feed/feed-news/rss',
            'https://pitchfork.com/feed/feed-album-reviews/rss',
        ],
    },
    'Decibel': {
        'tier': 1,
        'authority': 10,
        'region': 'US',
        'kind': 'editorial',
        'feeds': ['https://www.decibelmagazine.com/feed/'],
    },
    'Revolver': {
        'tier': 1,
        'authority': 8,
        'region': 'US',
        'kind': 'editorial',
        'feeds': ['https://www.revolvermag.com/feed/'],
    },
    'Metal Injection': {
        'tier': 1,
        'authority': 8,
        'region': 'US',
        'kind': 'editorial',
        'feeds': [
            'https://metalinjection.net/feed/',
        ],
    },
    'Loudwire': {
        'tier': 1,
        'authority': 7,
        'region': 'US',
        'kind': 'editorial',
        'feeds': ['https://loudwire.com/feed/'],
    },
    'Stereogum': {
        'tier': 1,
        'authority': 7,
        'region': 'US',
        'kind': 'editorial',
        'feeds': ['https://www.stereogum.com/feed/'],
    },
    'Consequence': {
        'tier': 1,
        'authority': 7,
        'region': 'US',
        'kind': 'editorial',
        'feeds': ['https://consequence.net/feed/'],
    },
    'BrooklynVegan': {
        'tier': 1,
        'authority': 6,
        'region': 'US',
        'kind': 'editorial',
        'feeds': ['https://www.brooklynvegan.com/feed/'],
    },
    'Kerrang': {
        'tier': 1,
        'authority': 9,
        'region': 'UK',
        'kind': 'editorial',
        'feeds': [
            'https://www.kerrang.com/feed',
            'https://www.kerrang.com/feed.rss',
        ],
    },
    'Louder': {
        'tier': 1,
        'authority': 8,
        'region': 'UK',
        'kind': 'editorial',
        'feeds': [
            'https://www.loudersound.com/rss',
            'https://www.loudersound.com/metal-hammer/feed',
        ],
    },
    'The Quietus': {
        'tier': 1,
        'authority': 8,
        'region': 'UK',
        'kind': 'editorial',
        'feeds': ['https://thequietus.com/feed/'],
    },
    'Metalitalia': {
        'tier': 1,
        'authority': 8,
        'region': 'IT',
        'kind': 'specialist',
        'feeds': ['https://metalitalia.com/feed/'],
    },
    'Metallus': {
        'tier': 1,
        'authority': 6,
        'region': 'IT',
        'kind': 'specialist',
        'feeds': ['https://metallus.it/feed'],
    },
}

SUBGENRES = (
    'heavy metal',
    'thrash metal',
    'death metal',
    'black metal',
    'doom metal',
    'sludge',
    'stoner metal',
    'progressive metal',
    'post-metal',
    'metalcore',
    'deathcore',
    'industrial metal',
    'nu metal',
    'alternative metal',
    'gothic metal',
    'speed metal',
    'symphonic metal',
    'avant-garde metal',
    'experimental metal',
)
